# Generated by Django 4.2.7 on 2024-05-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, unique=True)),
                ('h0', models.CharField(max_length=150)),
                ('content_h0', models.CharField(max_length=5000)),
                ('h1', models.CharField(max_length=150)),
                ('content_h1', models.CharField(max_length=5000)),
                ('h2', models.CharField(max_length=150)),
                ('content_h2', models.CharField(max_length=5000)),
                ('pub_date', models.DateField()),
                ('thumbnail', models.ImageField(height_field=100, upload_to='blog/blog_img', width_field=100)),
            ],
        ),
    ]
